---
- name: Uninstall release via Helm
  shell:  # noqa 301
    set -o errexit
    set -o pipefail
    set -o nounset

    helm uninstall {{ cert_manager_release_name }} --namespace {{ cert_manager_namespace }}

    exit 0
  run_once: true
  delegate_to: 127.0.0.1
  changed_when: false
  args:
    executable: "/bin/bash"

- name: Remove repository via Helm
  shell:  # noqa 301
    set -o errexit
    set -o pipefail
    set -o nounset

    helm repo remove {{ cert_manager_repo_name }}

    exit 0
  run_once: true
  delegate_to: 127.0.0.1
  changed_when: false
  args:
    executable: "/bin/bash"

- name: Delete namespace
  k8s:
    name: "{{ cert_manager_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  delegate_to: 127.0.0.1
  run_once: true
