---
- name: Ensure namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ cert_manager_namespace }}"
        labels:
          cert-manager.io/disable-validation: "true"
  delegate_to: 127.0.0.1
  run_once: true

- name: Register if Helm repository is installed
  command: helm search repo {{ cert_manager_chart_name }} -n {{ cert_manager_namespace }}
  register: cert_manager_repo_installed
  changed_when: false
  delegate_to: 127.0.0.1
  run_once: true

- name: Add Helm repository
  command: helm repo add {{ cert_manager_repo_name }} {{ cert_manager_chart_url }}
  changed_when: false
  delegate_to: 127.0.0.1
  run_once: true
  when: "cert_manager_repo_installed.stdout.find(cert_manager_chart_name) == -1"

- name: Update local Helm chart repository cache
  command: helm repo update -n {{ cert_manager_namespace }}
  changed_when: false
  delegate_to: 127.0.0.1
  run_once: true
