---
- name: Include prerequisites
  include_tasks: "tasks/prerequisites.yml"

- name: Create values
  set_fact:
    cert_manager_values_rendered="{% for option in cert_manager_values %}--set {{ option }} {% endfor %}"

- name: Upgrade release
  shell:
    set -o errexit
    set -o pipefail
    set -o nounset

    helm upgrade {{ cert_manager_release_name }} {{ cert_manager_chart_name }}
    --namespace {{ cert_manager_namespace }}
    --version {{ cert_manager_chart_version }}
    {{ cert_manager_values_rendered }}

    exit 0
  run_once: true
  delegate_to: 127.0.0.1
  changed_when: false
  args:
    executable: "/bin/bash"
